-- SQL Fix Script generated by DB Audit
-- USE WITH CAUTION - BACKUP FIRST!

ALTER TABLE `cloverTransactions` ADD COLUMN `cardLastFour` varchar(4)  ;
ALTER TABLE `cloverTransactions` ADD COLUMN `cardType` varchar(50)  ;
ALTER TABLE `cloverTransactions` ADD COLUMN `cloverOrderId` varchar(255)  ;
ALTER TABLE `cloverTransactions` ADD COLUMN `deviceName` varchar(255)  ;
ALTER TABLE `cloverTransactions` ADD COLUMN `notes` text  ;
ALTER TABLE `cloverTransactions` ADD COLUMN `receiptUrl` text  ;
ALTER TABLE `cloverTransactions` ADD COLUMN `status` enum('pending','processing','completed','failed','cancelled','refunded')  DEFAULT 'pending';
ALTER TABLE `cloverTransactions` ADD COLUMN `updatedAt` timestamp NOT NULL DEFAULT 'CURRENT_TIMESTAMP';

ALTER TABLE `subscriptions` ADD COLUMN `stripePriceId` varchar(255)  ;

-- ALTER TABLE `bankAccounts` DROP COLUMN `createdAt`; -- EXTRA COLUMN (review before dropping)
-- ALTER TABLE `bankAccounts` DROP COLUMN `currency`; -- EXTRA COLUMN (review before dropping)

-- ALTER TABLE `bankTransactions` DROP COLUMN `plaidTransactionId`; -- EXTRA COLUMN (review before dropping)
-- ALTER TABLE `bankTransactions` DROP COLUMN `updatedAt`; -- EXTRA COLUMN (review before dropping)

-- ALTER TABLE `cloverAccounts` DROP COLUMN `createdAt`; -- EXTRA COLUMN (review before dropping)

-- ALTER TABLE `cloverTransactions` DROP COLUMN `tipAmount`; -- EXTRA COLUMN (review before dropping)

-- ALTER TABLE `customers` DROP COLUMN `isActive`; -- EXTRA COLUMN (review before dropping)

-- ALTER TABLE `expenses` DROP COLUMN `isRecurring`; -- EXTRA COLUMN (review before dropping)
-- ALTER TABLE `expenses` DROP COLUMN `recurringFrequency`; -- EXTRA COLUMN (review before dropping)
-- ALTER TABLE `expenses` DROP COLUMN `updatedAt`; -- EXTRA COLUMN (review before dropping)

-- ALTER TABLE `journalEntries` DROP COLUMN `notes`; -- EXTRA COLUMN (review before dropping)
-- ALTER TABLE `journalEntries` DROP COLUMN `updatedAt`; -- EXTRA COLUMN (review before dropping)

-- ALTER TABLE `bankAccounts` MODIFY COLUMN `accountNumber` varchar(50); -- TYPE MISMATCH (review data first)
-- ALTER TABLE `bankAccounts` MODIFY COLUMN `accountType` varchar(50); -- TYPE MISMATCH (review data first)

-- ALTER TABLE `journalEntries` MODIFY COLUMN `reference` varchar(100); -- TYPE MISMATCH (review data first)

-- ALTER TABLE `passwordResetCodes` MODIFY COLUMN `code` varchar(6); -- TYPE MISMATCH (review data first)

-- ALTER TABLE `users` MODIFY COLUMN `role` enum('user','admin'); -- TYPE MISMATCH (review data first)

-- ALTER TABLE `accounts` MODIFY COLUMN `id` ... NOT NULL; -- NULL MISMATCH (review data first)
-- ALTER TABLE `accounts` MODIFY COLUMN `type` ... NOT NULL; -- NULL MISMATCH (review data first)

-- ALTER TABLE `bankAccounts` MODIFY COLUMN `id` ... NOT NULL; -- NULL MISMATCH (review data first)

-- ALTER TABLE `bankTransactions` MODIFY COLUMN `category` ... NOT NULL; -- NULL MISMATCH (review data first)
-- ALTER TABLE `bankTransactions` MODIFY COLUMN `id` ... NOT NULL; -- NULL MISMATCH (review data first)
-- ALTER TABLE `bankTransactions` MODIFY COLUMN `type` ... NOT NULL; -- NULL MISMATCH (review data first)

-- ALTER TABLE `cloverAccounts` MODIFY COLUMN `id` ... NOT NULL; -- NULL MISMATCH (review data first)

-- ALTER TABLE `cloverTransactions` MODIFY COLUMN `id` ... NOT NULL; -- NULL MISMATCH (review data first)

-- ALTER TABLE `companySettings` MODIFY COLUMN `companyName` ... NULLABLE; -- NULL MISMATCH (review data first)
-- ALTER TABLE `companySettings` MODIFY COLUMN `id` ... NOT NULL; -- NULL MISMATCH (review data first)

-- ALTER TABLE `customers` MODIFY COLUMN `clientType` ... NOT NULL; -- NULL MISMATCH (review data first)
-- ALTER TABLE `customers` MODIFY COLUMN `id` ... NOT NULL; -- NULL MISMATCH (review data first)

-- ALTER TABLE `expenses` MODIFY COLUMN `createdBy` ... NULLABLE; -- NULL MISMATCH (review data first)
-- ALTER TABLE `expenses` MODIFY COLUMN `id` ... NOT NULL; -- NULL MISMATCH (review data first)
-- ALTER TABLE `expenses` MODIFY COLUMN `paymentMethod` ... NOT NULL; -- NULL MISMATCH (review data first)

-- ALTER TABLE `journalEntries` MODIFY COLUMN `createdBy` ... NULLABLE; -- NULL MISMATCH (review data first)
-- ALTER TABLE `journalEntries` MODIFY COLUMN `id` ... NOT NULL; -- NULL MISMATCH (review data first)

-- ALTER TABLE `journalEntryLines` MODIFY COLUMN `id` ... NOT NULL; -- NULL MISMATCH (review data first)

-- ALTER TABLE `passwordResetCodes` MODIFY COLUMN `createdAt` ... NOT NULL; -- NULL MISMATCH (review data first)
-- ALTER TABLE `passwordResetCodes` MODIFY COLUMN `id` ... NOT NULL; -- NULL MISMATCH (review data first)

-- ALTER TABLE `paymentRecords` MODIFY COLUMN `id` ... NOT NULL; -- NULL MISMATCH (review data first)
-- ALTER TABLE `paymentRecords` MODIFY COLUMN `method` ... NOT NULL; -- NULL MISMATCH (review data first)
-- ALTER TABLE `paymentRecords` MODIFY COLUMN `status` ... NOT NULL; -- NULL MISMATCH (review data first)

-- ALTER TABLE `periodClosures` MODIFY COLUMN `id` ... NOT NULL; -- NULL MISMATCH (review data first)

-- ALTER TABLE `saleServices` MODIFY COLUMN `id` ... NOT NULL; -- NULL MISMATCH (review data first)

-- ALTER TABLE `sales` MODIFY COLUMN `id` ... NOT NULL; -- NULL MISMATCH (review data first)
-- ALTER TABLE `sales` MODIFY COLUMN `paymentMethod` ... NOT NULL; -- NULL MISMATCH (review data first)
-- ALTER TABLE `sales` MODIFY COLUMN `status` ... NOT NULL; -- NULL MISMATCH (review data first)

-- ALTER TABLE `services` MODIFY COLUMN `id` ... NOT NULL; -- NULL MISMATCH (review data first)

-- ALTER TABLE `subscriptionPayments` MODIFY COLUMN `id` ... NOT NULL; -- NULL MISMATCH (review data first)
-- ALTER TABLE `subscriptionPayments` MODIFY COLUMN `plan` ... NOT NULL; -- NULL MISMATCH (review data first)
-- ALTER TABLE `subscriptionPayments` MODIFY COLUMN `status` ... NOT NULL; -- NULL MISMATCH (review data first)

-- ALTER TABLE `subscriptions` MODIFY COLUMN `id` ... NOT NULL; -- NULL MISMATCH (review data first)
-- ALTER TABLE `subscriptions` MODIFY COLUMN `plan` ... NOT NULL; -- NULL MISMATCH (review data first)
-- ALTER TABLE `subscriptions` MODIFY COLUMN `status` ... NOT NULL; -- NULL MISMATCH (review data first)

-- ALTER TABLE `users` MODIFY COLUMN `email` ... NULLABLE; -- NULL MISMATCH (review data first)
-- ALTER TABLE `users` MODIFY COLUMN `id` ... NOT NULL; -- NULL MISMATCH (review data first)
-- ALTER TABLE `users` MODIFY COLUMN `lastSignInAt` ... NOT NULL; -- NULL MISMATCH (review data first)
